repos:
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.0.4
    hooks:
      - id: pycln
        args: [--config=.pyproject.toml]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: Formatting python (black)
        language_version: python3
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: .*\.py
        args: [--settings-path=.pyproject.toml]
  - repo: https://github.com/prettier/pre-commit
    rev: v2.1.1
    hooks:
      - id: prettier
        name: Formatting javascript (prettier)
        files: ^frontend/.*
  - repo: https://github.com/ilgigrad/pre-commit-js-beautify
    rev: 1b4c92b609c361a1047b73eff8db5d993f53db83
    hooks:
      - id: js-beautify
        name: Formatting html (js-beautify)
        files: ^templates/.*
        args: [
          '--replace',
          '--indent-size=2',
          '--wrap-line-length=88',
          '--templating=django',
          '--quiet',
        ]
