name: Check code style
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: |
          pip install pre-commit==2.15.0
          pre-commit install

      - name: Run pre-commit hooks
        run: pre-commit run --all-files
