name: Run all tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2

      - name: Set up npm
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      #- name: Update npm
      #  run: npm install -g npm

      #- name: Install js packages
      #  run: npm install
      #  working-directory: ./frontend

      # - name: Transpile js source
      #   run: npm run webpack
      #   working-directory: ./frontend
      #
      # - name: Run js tests
      #   run: ./node_modules/jest/bin/jest.js
      #   working-directory: ./frontend

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run python tests
        run: python3 manage.py test
        env:
          DJANGO_SETTINGS_MODULE: ubbc.test_settings

      - name: Check for missing migrations
        run: python3 .github/scripts/check_migrations.py
